import {ReactNode} from "react";
import styles from "@/app/WelcomeCard.module.css";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="es">
      <body className={styles.body}>{children}</body>
    </html>
  )
}
